tap thoughtbot/formulae
install rcm

install ansible
install ctags-exuberant
install fzf
install git
install git-extras
install httpie
install hub
install id3v2
install imagemagick
install irssi
install libxml2
install macvim
install media-info
install mongodb
install mp3check
install mp3info
install mplayer
install mysql
install node
install postgresql
install rbenv-default-gems
install reattach-to-user-namespace
install redis
install rename
install shellcheck
install taglib
install the_silver_searcher
install tig
install tmux
install tree
install vim
install wget
install youtube-dl
install zsh-completions

tap mpv-player/mpv
install mpv

tap phinze/cask
install brew-cask
cask install adapter
cask install appcleaner
cask install qlstephen
cask install quicklook-json
cask install rowanj-gitx

tap caskroom/fonts
cask install font-dejavu-sans
cask install font-droid-sans-mono
cask install font-inconsolata

linkapps
cleanup
